window.scheduleData = [
    {
        date:"2017-09-23",
        list:[
            {
                title:"aaaaaaa",
                time:"10:00",
                list:[
                    "something",
                    "something"
                ]
            },
            {
                title:"bbbbbbb",
                time:"11:00",
                list:[
                    "something",
                    "something"
                ]
            }
        ]
    },
    {
        date:"2017-09-24",
        list:[
            {
                title:"cccccc",
                time:"10:00",
                list:[
                    "something",
                    "something"
                ]
            },
            {
                title:"ddddd",
                time:{
                    startTime:"11:00",
                    endTime:"12:00"
                }
            }
        ]
    },
    {
        date:"2017-09-25"
    },
    {
        date:"2017-09-26",
        list:[
            {
                title:"cccccc",
                time:"10:00",
                list:[
                    "something",
                    "something"
                ]
            },
            {
                title:"ddddd",
                time:{
                    startTime:"11:00",
                    endTime:"12:00"
                }
            }
        ]
    },
    {
        date:{
            startDate:"2017-09-27",
            endDate:"2017-09-29"
        },
        list:[
            {
                title:"dddddddddd"
            }
        ]
    }
]